version: '3.8'

services:
  axiom-web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=6000
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      # Montar a pasta de imagens para facilitar a substituição de imagens
      - ./client/public/images:/app/dist/images:ro
    
# Instruções para uso:
# 1. Desenvolvimento local: docker-compose up
# 2. Deploy no EasyPanel: use o Dockerfile diretamente