version: '3.8'

services:
  axiom-web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=6000
      - HOST=0.0.0.0
    
# Instruções para uso:
# 1. Desenvolvimento local: docker-compose up
# 2. Deploy no EasyPanel: use o Dockerfile diretamente